version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    volumes:
      # Yerel klasördeki "combined-swagger.json" dosyasını
      # konteyner içinde "/usr/share/nginx/html/swagger.json" olarak mount ediyoruz
      - ./combined-swagger.json:/usr/share/nginx/html/swagger.json
    environment:
      # "SWAGGER_JSON" değeri, konteyner içindeki dosya yolunu gösteriyor
      - SWAGGER_JSON=swagger.json
      - API_URL=http://localhost:8000/swagger.json # Swagger UI’a açıkça HTTP kullanmasını söylüyoruz
      - USE_BASE_URL=true
    # ports:
    #   - '8086:8080'

volumes:
  grafana-data:
